export const BOOKING_TYPES = {
  FERRY: 'FERRY',
  CRUISE: 'CRUISE',
  STAY: 'STAY',
  ACTIVITY: 'ACTIVITY',
  PACKAGE: 'PACKAGE',
};

export const BOOKING_STATUS = {
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
  PENDING: 'PENDING',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  EXPIRED: 'EXPIRED',
  REFUNDED: 'REFUNDED',
  CHECKED_IN: 'CHECKED_IN',
};

export const SCHEDULE_STATUS = {
  SCHEDULED: 'SCHEDULED',
  ON_TIME: 'ON_TIME',
  BOARDING: 'BOARDING',
  DELAYED: 'DELAYED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
};
