import express from 'express';
import authRoutes from './authRoutes.js';
import userRoutes from './userRoutes.js';
import destinationRoutes from './destinationRoutes.js';
import ferryRoutes from './ferryRoutes.js';
import cruiseRoutes from './cruiseRoutes.js';
import stayRoutes from './stayRoutes.js';
import bookingRoutes from './bookingRoutes.js';
import blogRoutes from './blogRoutes.js';
import contactRoutes from './contactRoutes.js';
import inquiryRoutes from './inquiryRoutes.js';
import uploadRoutes from './uploadRoutes.js';
import reviewRoutes from './reviewRoutes.js';
import dashboardRoutes from './dashboardRoutes.js';
import paymentRoutes from './paymentRoutes.js';
import placeRoutes from './placeRoutes.js';
import activityRoutes from './activityRoutes.js';
import packageRoutes from './packageRoutes.js';
import receptionRoutes from './receptionRoutes.js';
import filmRoutes from './filmRoutes.js';
import testimonialRoutes from './testimonialRoutes.js';
import itineraryRoutes from './itineraryRoutes.js';
import masterRoutes from './masterRoutes.js';
import galleryRoutes from './galleryRoutes.js';
import settingRoutes from './settingRoutes.js';

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/destinations', destinationRoutes);
router.use('/ferries', ferryRoutes);
router.use('/cruises', cruiseRoutes);
router.use('/stays', stayRoutes);
router.use('/bookings', bookingRoutes);
router.use('/blogs', blogRoutes);
router.use('/contact', contactRoutes);
router.use('/inquiries', inquiryRoutes);
router.use('/upload', uploadRoutes);
router.use('/reviews', reviewRoutes);
router.use('/payments', paymentRoutes);
router.use('/places', placeRoutes);
router.use('/activities', activityRoutes);
router.use('/packages', packageRoutes);
router.use('/film-chapters', filmRoutes);
router.use('/testimonials', testimonialRoutes);
router.use('/itineraries', itineraryRoutes);
router.use('/master', masterRoutes);
router.use('/gallery', galleryRoutes);
router.use('/admin/dashboard', dashboardRoutes);
router.use('/admin/settings', settingRoutes);
router.use('/settings', settingRoutes);
router.use('/reception', receptionRoutes);

export default router;
